export const UserRegisterTypes = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const UserVerifyTypes = {
  USER_VERIFY_REQUEST: "USER_VERIFY_REQUEST",
  USER_VERIFY_SUCCESS: "USER_VERIFY_SUCCESS",
  USER_VERIFY_FAIL: "USER_VERIFY_FAIL",
};

export const UserLoginTypes = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
};

export const UserForgotPasswordTypes = {
  USER_FORGOT_PASSWORD_REQUEST: "USER_FORGOR_PASSWORD_REQUEST",
  USER_FORGOT_PASSWORD_SUCCESS: "USER_FORGOR_PASSWORD_SUCCESS",
  USER_FORGOT_PASSWORD_FAIL: "USER_FORGOR_PASSWORD_FAIL",
};
